PIVerror = "0.1"
SaveIMdeform = "0"
batchname = "PIV_base"
channel = "1"
clientversion = "2.7.0"
cpass = "1"
datout = "0"
exp_L = ""
exp_M = ""
exp_NA = ""
exp_ROI = "0.10706,0.1604"
exp_Re = ""
exp_St = ""
exp_date = ""
exp_density = "1.2"
exp_depthoffocus = ""
exp_diffractiondiameter = ""
exp_lensfnum = ""
exp_lensfocal = ""
exp_micro = "0"
exp_n = ""
exp_notes = ["Camera Description:", "", "Lens Description:", "", "Notes:", ""]
exp_partD = ""
exp_partdensity = ""
exp_pixelsize = ""
exp_surfacetension = "0"
exp_v0 = ""
exp_viscosity = "1.308e-3"
exp_wavelength = ".532"
framestep = "3"
imbase = "LA"
imbase2 = "LA"
imcstep = "1"
imdirec = "S:\\users\\shocktube\\runs\\2022\\11\\8\\R2\\"
imdirec2 = "S:\\users\\shocktube\\runs\\2022\\11\\8\\R2\\"
imext = "tif"
imfend = "1"
imfstart = "1"
imfstep = "1"
iminterp = "3"
imzeros = "6"
input_vel_type = "none"
input_velbase = ""
input_veldirec = ""
input_velocity = ""
maskbase = "maskfor_Img_"
maskdirec = "C:\\Users\\aames\\Documents\\MATLAB\\prana-master"
maskext = "tif"
maskfstart = "1"
maskfstep = "1"
masktype = "none"
maskzeros = "6"
method = "3"
multiplematout = "1"
numcams = "1"
outdirec = "S:\\users\\shocktube\\runs\\2022\\11\\8\\"
outputpassbase = "PIV"
par = "0"
parprocessors = "2"
passes = "3"
ptv_version = "2.0.beta.r2012.11.26"
runPIV = "1"
splash = "1"
staticmaskname = "S:\\users\\shocktube\\runs\\2022\\6\\24\\staticmask.tif"
velinterp = "3"
version = "2.8.0.beta.r2021.01.19"
wrmag = "24.332"
wrsamp = "1"
wrsep = "3"

[ID]
imthresh = "10"
method = "2"
runid = "0"
save_dir = "C:\\Users\\aames\\Documents\\MATLAB\\prana-master\\ID\\"
savebase = "PIVID_"

[PIV0]
BWO = "0,0"
RPCd = "2.8,2.8"
bootstrap = "0"
bootstrap_iterations = "700"
bootstrap_passes = "12"
bootstrap_percentsampled = "15"
corr = "RPC"
corrpeak_absthresh = "0"
corrpeak_ratiothresh = "1.2"
corrpeaknum = "1"
corrpeaktest = "0"
deform_conv = "0.1"
deform_max = "1"
deform_min = "1"
frac_filt = "1"
grid_angle = "0,90"
gridbuf = "8,8"
gridres = "8,8"
gridtype = "1"
imuncertainty = "0"
mcuncertainty = "0"
miuncertainty = "0"
outbase = "PIV_pass0_"
peaklocator = "1"
ppruncertainty = "0"
savepeakinfo = "0"
savepeakmag = "0"
savepeakvel = "0"
saveplane = "0"
thresh = "0"
uncertaintyestimate = "0"
uod = "1"
uod_thresh = "3,2"
uod_type = "2"
uod_window = "3,3;3,3"
val = "0"
valextrapeaks = "0"
valuthresh = "-16,16"
valvthresh = "-16,16"
velsmooth = "0"
velsmoothfilt = "2"
winauto = "1"
winoverlap = "75,75"
winres = "32,32; 32,32"
winsize = "64,64"
write = "1"
zeromean = "1"

[PIV1]
BWO = "0,0"
RPCd = "2.8,2.8"
bootstrap = "0"
bootstrap_iterations = "700"
bootstrap_passes = "12"
bootstrap_percentsampled = "15"
corr = "RPC"
corrpeak_absthresh = "0"
corrpeak_ratiothresh = "1.2"
corrpeaknum = "2"
corrpeaktest = "0"
deform_conv = "0.1"
deform_max = "3"
deform_min = "2"
frac_filt = "1"
grid_angle = "0,90"
gridbuf = "8,8"
gridres = "64,64"
gridtype = "2"
imuncertainty = "0"
mcuncertainty = "0"
miuncertainty = "0"
outbase = "PIVpass1_"
peaklocator = "1"
ppruncertainty = "0"
savepeakinfo = "1"
savepeakmag = "1"
savepeakvel = "1"
saveplane = "0"
thresh = "0"
uncertaintyestimate = "0"
uod = "1"
uod_thresh = "3,2"
uod_type = "2"
uod_window = "3,3;3,3"
val = "1"
valextrapeaks = "1"
valuthresh = "-16,16"
valvthresh = "-16,16"
velsmooth = "1"
velsmoothfilt = "2"
winauto = "1"
winoverlap = "50,50"
winres = "128,128;128,128"
winsize = "256,256"
write = "1"
zeromean = "1"

[PIV2]
BWO = "0,0"
RPCd = "2.8,2.8"
bootstrap = "0"
bootstrap_iterations = "700"
bootstrap_passes = "12"
bootstrap_percentsampled = "15"
corr = "RPC"
corrpeak_absthresh = "0"
corrpeak_ratiothresh = "1.2"
corrpeaknum = "2"
corrpeaktest = "0"
deform_conv = "0.1"
deform_max = "3"
deform_min = "2"
frac_filt = "1"
grid_angle = "0,90"
gridbuf = "8,8"
gridres = "32,32"
gridtype = "2"
imuncertainty = "0"
mcuncertainty = "0"
miuncertainty = "0"
outbase = "PIVpass2_"
peaklocator = "1"
ppruncertainty = "0"
savepeakinfo = "1"
savepeakmag = "1"
savepeakvel = "1"
saveplane = "0"
thresh = "0"
uncertaintyestimate = "0"
uod = "1"
uod_thresh = "3,2"
uod_type = "2"
uod_window = "3,3;3,3"
val = "1"
valextrapeaks = "1"
valuthresh = "-16,16"
valvthresh = "-16,16"
velsmooth = "1"
velsmoothfilt = "2"
winauto = "1"
winoverlap = "50,50"
winres = "64,64;64,64"
winsize = "128,128"
write = "1"
zeromean = "1"

[PIV3]
BWO = "0,0"
RPCd = "2.8,2.8"
bootstrap = "0"
bootstrap_iterations = "700"
bootstrap_passes = "12"
bootstrap_percentsampled = "15"
corr = "RPC"
corrpeak_absthresh = "0"
corrpeak_ratiothresh = "1.2"
corrpeaknum = "2"
corrpeaktest = "0"
deform_conv = "0.1"
deform_max = "5"
deform_min = "2"
frac_filt = "1"
grid_angle = "0,90"
gridbuf = "8,8"
gridres = "16,16"
gridtype = "2"
imuncertainty = "0"
mcuncertainty = "0"
miuncertainty = "0"
outbase = "PIVpass3_"
peaklocator = "1"
ppruncertainty = 1.0
savepeakinfo = "1"
savepeakmag = "1"
savepeakvel = "1"
saveplane = "0"
thresh = "0"
uncertaintyestimate = "1"
uod = "1"
uod_thresh = "3,2"
uod_type = "2"
uod_window = "3,3;3,3"
val = "1"
valextrapeaks = "1"
valuthresh = "-16,16"
valvthresh = "-16,16"
velsmooth = "0"
velsmoothfilt = "2"
winauto = "1"
winoverlap = "50,50"
winres = "32,32;32,32"
winsize = "64,64"
write = "1"
zeromean = "1"

[Size]
method = "GEO"
min_area = "0"
runsize = "0"
save_dir = "C:\\Users\\aames\\Documents\\MATLAB\\prana-master\\Size\\"
savebase = "PIVSize_"
std = "4"

[Track]
PIVweight = "0.5"
disweight = "1.0"
estradius = "15"
estweight = ".1"
intensityweight = "0.5"
iterations = "3"
method = "2"
prediction = "1"
radius = "15"
runtrack = "0"
save_dir = "C:\\Users\\aames\\Documents\\MATLAB\\prana-master\\Track\\"
savebase = "PIVTrack_"
sizeweight = "0.5"
trackdat = "0"
trackmat = "1"
vectors = "3"

    [Track.PIVprops]
    load_dir = "C:\\Users\\aames\\Documents\\MATLAB\\prana-master\\"

    [Track.valprops]
    MAD_U = "1,0.75,0"
    MAD_V = "1,0.75,0"
    run = "1"
    valcoef = "0,0,0.2"
    valrad = "20,20,0"
